### ISSUE TITLE
Links to resources html in report pages instead of https

### ISSUE THREAD

**Issue by pedrodelgado81** [web-innovate/bootstraped-multi-test-results-report#28]
The links to the resources in html reports are  http and  https. In an https server, report pages doesn't work because server doesn't import the resources into http url (security check).

I changed the url of the resources in this file 
web-innovate-bootstraped-multi-test-results-report-434d1b2\testng-reporting-handlebars\src\main\resources\testng-reporting\requiredScripts.hbs from http to https.

The http resources are: 
http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
http://code.highcharts.com/highcharts.js
http://code.highcharts.com/highcharts-3d.js
http://code.highcharts.com/modules/exporting.js

This must be changed in the others report tools.

**Comment by BogdanLivadariu** [comment]
@pedrodelgado81 this issue should get fixed with the next version 1.4.10 that I plan to release in the next hour
https://github.com/web-innovate/bootstraped-multi-test-results-report/pull/29

**Comment by pedrodelgado81** [comment]
Great!

**Comment by BogdanLivadariu** [comment]
@pedrodelgado81  you could join: https://gitter.im/web-innovate/bootstraped-multi-test-results-report?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge for chatting :)
and I could give you there the 1.4.10 hpi

**Comment by BogdanLivadariu** [comment]
or you could download it from here : http://repo.jenkins-ci.org/public/com/github/bogdanlivadariu/bootstraped-multi-test-results-report/1.4.10/bootstraped-multi-test-results-report-1.4.10.hpi

**Comment by pedrodelgado81** [comment]
Not Fixed, the problem still persist. The http links must be changed to https. To make it work over https  connection.

`<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/highcharts-3d.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<link href="http://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="http://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>`

Must change to https.

**Comment by BogdanLivadariu** [comment]
@pedrodelgado81 silly me, I got it the other way around :)

**Comment by pedrodelgado81** [comment]
Working on 1.4.11. Great Job!
